classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.ubuntu
- system.linux.system.repo.glusterfs
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.xtrabackup.server.single
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.salt.minion.cert.k8s_server
- system.reclass.storage.system.kubernetes_control_cluster
- cluster.mcp_k8s.infra.maas
- cluster.mcp_k8s.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$PiDbbXFp$YVuXjZ/MbknNJeZm71y5IL.trU6Xw04Fgsve7XBmijSbAde8FQq2kRosVynBsqEHoFaM1mpysEZ/PaPIQsh.G0"
    salt_master_host: ${_param:infra_config_deploy_address}
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
            deploy_address:
              value_template: <<node_deploy_ip>>
        kubernetes_compute:
          expression: <<node_hostname>>__startswith__cmp
          node_class:
            value_template:
              - cluster.<<node_cluster>>.kubernetes.compute
          node_param:
            deploy_address:
              value_template: <<node_deploy_ip>>
      data_source:
        engine: local
      node:
        kubernetes_control_node01:
          params:
            tenant_address: ${_param:kubernetes_control_node01_tenant_address}
        kubernetes_control_node02:
          params:
            tenant_address: ${_param:kubernetes_control_node02_tenant_address}
        kubernetes_control_node03:
          params:
            tenant_address: ${_param:kubernetes_control_node03_tenant_address}
        opencontrail_control_node01:
          params:
            rabbitmq_cluster_role: master
        opencontrail_control_node02:
          params:
            rabbitmq_cluster_role: slave
        opencontrail_control_node03:
          params:
            rabbitmq_cluster_role: slave
