
parameters:
  _param:
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: dc9EngqZoxW46pfr
    kubernetes_admin_token: QUOPgpaOAWSSiCkAg8z6jw5qZWIWFDrX
    kubernetes_kubelet_token: M18wP1j7ChU2ghHpgD0b9BESapTJUWU5
    kubernetes_kube-proxy_token: 1wPShb30RYgubOUV4H2YLgyQWqpeQqSD
    kubernetes_scheduler_token: 7UqOumGtSWEuYIgvmoUEJmzdgFi4m5kN
    kubernetes_controller-manager_token: 3c6yi7h4Q3NXYmft4vrpSFQZdycO7aOR
    kubernetes_dns_token: qvvE2dxNRC1XjYcmYxQYQ6GRejuv2CK1
    etcd_initial_token: 5ZBgAiK3hmAd5QQxRPGRwIMnHn8RsSta

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_control_hostname: ctl
    kubernetes_control_address: 10.0.1.10
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node02_hostname: ctl02
    kubernetes_control_node03_hostname: ctl03
    kubernetes_control_node01_address: 10.0.1.11
    kubernetes_control_node02_address: 10.0.1.12
    kubernetes_control_node03_address: 10.0.1.13

    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}

    # etcd stuff
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001

    kubernetes_virtlet_enabled: False
    openstack_control_address: None
    keystone_admin_password: None
    openstack_version: None
    keystone_service_token: None
    openstack_region: None
    kubernetes_control_node01_tenant_address: 10.0.2.11
    kubernetes_control_node02_tenant_address: 10.0.2.12
    kubernetes_control_node03_tenant_address: 10.0.2.13

  linux:
    network:
      host:
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
